name: Fancrew Monitor Check

on:
  schedule:
    - cron: '*/15 * * * *'  # 毎時15分間隔で実行
  workflow_dispatch:        # 手動実行も可能

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python check_monitor.py
